name          'example42-nova'
version       '3.0.0-alpha2'
source        'https://github.com/example42/puppet-nova'
author        'Alessandro Franceschi'
license       'Apache License, Version 2.0'
summary       'This module installs and manages nova'
description   'This module installs and manages nova'
project_page  'http://www.example42.com'
dependency    'puppetlabs/stdlib'
dependency    'example42/stdmod'
